framework:
  rate_limiter:
    public_api:
      policy: 'sliding_window'
      limit: 600
      interval: '60 minutes'
    anonymous_api:
      policy: 'sliding_window'
      limit: 60
      interval: '60 minutes'
    authenticated_personal_api:
      policy: 'sliding_window'
      limit: 120
      interval: '2 hours'
    authenticated_api:
      policy: 'token_bucket'
      limit: 10000
      rate: { interval: '15 minutes', amount: 1000 }
    blackboard_edit_slide:
      policy: 'token_bucket'
      limit: 10
      rate: { interval: '2 minutes', amount: 1 }
    blackboard_edit_fixed:
      policy: 'fixed_window'
      limit: 100
      interval: '24 hours'
    forum_thread_creation:
      policy: 'token_bucket'
      limit: 10
      rate: { interval: '10 minutes', amount: 1 }
    report_to_moderation:
      policy: 'fixed_window'
      limit: 20
      interval: '12 hours'
    report_to_moderation_limited:
      policy: 'fixed_window'
      limit: 2
      interval: '60 hours'
    report_to_gitlab:
      policy: 'fixed_window'
      limit: 2
      interval: '6 hours'