monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [403, 404, 405, 429]
            channels: ["!night", "!admin"]
        night:
            type: fingers_crossed
            action_level: debug
            handler: rotation_night
            channels: ["night"]
        admin:
            type: fingers_crossed
            action_level: debug
            handler: rotation_admin
            channels: [ "admin" ]
        rotation_night:
            type: rotating_file
            path: "%kernel.logs_dir%/night/%kernel.environment%.log"
            level: debug
            max_files: 14
        rotation_admin:
            type: rotating_file
            path: "%kernel.logs_dir%/admin/%kernel.environment%.log"
            level: debug
            max_files: 14
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: null
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
