parameters:
  events:
    arma:
      trigger:
        type: datetime
        begin: 12-04 00:00
        end: 12-05 00:00
      conf:
        css: 'arma'
        event_dig:
          desert:
            group: ~
            chance: ~
          ruins:
        hooks:
          watchtower: 'App\Structures\Hook::watchtower_arma'
          door: 'App\Structures\Hook::door_arma'
          night_before: 'App\Structures\Hook::night_arma'
    christmas:
      trigger:
        type: datetime
        begin: 12-20 00:00
        end: 01-07 00:00
      conf:
        css: 'christmas'
        event_dig:
          desert:
            group: 'christmas_dig'
            chance: 0.4
          ruins:
            - {name: 'post', group: 'christmas_dig_post', chance: 0.5}
        hooks:
          night_after: 'App\Structures\Hook::night_xmas'
          night_none: 'App\Structures\Hook::night_xmas'