parameters:
  rules:
    default:
      allow_local_conf: true

      open_town_limit: 5
      lock_door_until_full: false

      well:       { min: 90, max: 180 }
      map:        { min: 25, max:  27, margin: 0.25 }
      population: { min: 40, max:  40 }

      ruins: 20
      explorable_ruins: 1

      explorable_ruin_params:
        complexity: 0.9
        convolution: 0.2
        cruelty: 0.06
        rooms: 10
        room_spacing: 4
        lock_distance: 10
        item_fillrate: 11
        max_distance: 12
        zombies:
          initial: 10
          daily: 3

      initial_buildings:  []
      unlocked_buildings: []

      bank_abuse:
        limit: 5
        chaos_limit: 10
        base_range_min: 5
        lock_range_min: 15

      times:
        digging:
          normal: '+2hour'
          collec: '+1hour30min'
        exploration:
          normal: '+5min'
          collec: '+7min30sec'

      initial_chest: ['beta_drug_#00']
      distribute_items: ['bplan_box_e_#00', 'bplan_box_e_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'firework_powder_#00','firework_tube_#00','firework_box_#00','firework_box_#00']
      instant_pictos: ['r_rp_#00', 'r_sandb_#00', 'r_ban_#00', 'r_theft_#00', 'r_collec_#00']

      distribution_distance:
        - item: 'bplan_box_e_#00'
          min: 9
          max: 21
        - item: 'bplan_box_#00'
          min: 6
          max: 15
        - item: 'firework_powder_#00'
          min: 6
          max: 15
        - item: 'firework_tube_#00'
          min: 6
          max: 15
        - item: 'firework_box_#00'
          min: 6
          max: 15

      modifiers:
        watchtower_estimation_threshold: 33
        allow_redig: false
        assemble_items_from_floor: false
        preview_item_assemblage: false
        infection_death_chance: 0.5
        wound_terror_penalty: 0.05
        poison:
          stack_poisoned_items: false
          transgress: false
        citizen_attack:
          ap: 5
          injury: 0.5
          protection: false
        carry_extra_bag: false
        meaty_bones_within_town: false
        building_attack_damage: false
        destroy_defense_objects_attack: false
        camping:
          default_bonus: 0
          map: 'normal'
        red_soul_max_factor: 1.2
        wind_distance: 2
        strict_picto_distribution: false
        sandball_nastyness: 0.1
        massive_respawn_factor: 1

      features:
        camping: true
        words_of_heros: true
        escort:
          enabled: true
          max: 4
        nightmode: true
        shaman: 'normal'
        xml_feed: true
        ghoul_mode: normal
        all_poison: false
        shun: true
        ghoul: true
        nightwatch:
          enabled: true
          instant: false
        improveddump: true
        attacks: 'normal'
        give_all_pictos: true
        give_soulpoints: true
        last_death: 'r_surlst_#00'
        survival_picto: null

      disabled_jobs: ['shaman']
      disabled_roles: []
      disabled_buildings: ['small_vaudoudoll_#00', 'small_bokorsword_#00', 'small_spiritmirage_#00','small_holyrain_#00']
      
    small:
      map:  { min: 12, max: 14, margin: 0.25 }
      ruins: 10
      explorable_ruins: 0

      initial_buildings:  ['small_refine_#00','small_door_closed_#00','item_tagger_#00']
      unlocked_buildings: ['small_gather_#02']

      distribute_items:
        replace: ['bplan_box_e_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00']

      distribution_distance:
        replace: []

      instant_pictos:
        merge: ['r_guide_#00', 'r_guard_#00']

      modifiers:
        watchtower_estimation_threshold: 0
        citizen_attack:
          protection: true
        wind_distance: -1
        strict_picto_distribution: true
        sandball_nastyness: 0.0
        massive_respawn_factor: 0.5

      features:
        shaman: 'none'
      
      disabled_roles: ['shaman']

    remote:

    panda:
      well: { min: 60, max: 90 }

      modifiers:
        infection_death_chance: 0.75
        wound_terror_penalty: 0.2
        building_attack_damage: true
        destroy_defense_objects_attack: true
        citizen_attack:
          ap: 4
          injury: 0.6
        camping:
          default_bonus: -14
          map: 'hard'
        red_soul_max_factor: 666
        sandball_nastyness: 0.85

      features:
        attacks: 'hard'
        last_death: 'r_suhard_#00'
        survival_picto: 'r_pande_#00'

      explorable_ruins: 2

      times:
        exploration:
          normal: '+3min30sec'
          collec: '+5min15sec'

      explorable_ruin_params:
        max_distance: 100

    custom:
      open_town_limit: 2
      lock_door_until_full: true
      give_all_pictos: false
      give_soulpoints: false