parameters:
  rules_local: []
  rules:
    default:
      allow_local_conf: true

      open_town_limit: 7
      open_town_grace: 30
      stranger_day_limit: -1
      stranger_citizen_limit: 0
      lock_door_until_full: false

      well:       { min: 90, max: 180 }
      map:        { min: 25, max:  27, margin: 0.25 }
      population: { min: 40, max:  40 }

      margin_custom:
        enabled: false
        north: 25
        south: 25
        west: 25
        east: 25

      zone_items:
        min: 5
        max: 10
        refresh_max: 8
        plan_limits:
          bag: 3
      ruin_items:
        min: 8
        max: 16

      ruins: 20
      explorable_ruins: 1

      map_params:
        free_spawn_zones:
          count: 2
          probability: 0.1
        buried_ruins:
          probability: 0.5
          digs: { min: 1, max: 19 }
        dig_chances:
          base: 0.6
          depleted: 0.35

      explorable_ruin_params:
        complexity: 0.9
        convolution: 0.2
        cruelty: 0.06
        room_config:
          lock: 10
          distance: 5
          spacing: 4
          total: 15
          min: 5
        item_fillrate: 7
        max_distance: 10
        floors: 2
        plan_limits:
          unusual: -1
          rare: -1
          epic: -1
        zombies:
          initial: 10
          daily: 5

      initial_buildings:  []
      unlocked_buildings: []

      spiritual_guide:
        enabled: false
        sp_limit: 0
        citizen: 0

      bank_abuse:
        limit: 5
        chaos_limit: 10
        base_range_min: 5
        lock_range_min: 15

      times:
        digging:
          normal: '+2hour'
          collec: '+1hour30min'
        exploration:
          normal: '+5min'
          collec: '+7min30sec'

      initial_chest: []
      distribute_items: ['bplan_box_e_#00', 'bplan_box_e_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'firework_powder_#00','firework_tube_#00','firework_box_#00','firework_box_#00']
      instant_pictos: ['r_rp_#00', 'r_sandb_#00', 'r_ban_#00', 'r_theft_#00', 'r_collec_#00']

      distribution_distance:
        - item: 'bplan_box_e_#00'
          min: 9
          max: 21
        - item: 'bplan_box_#00'
          min: 6
          max: 15
        - item: 'firework_powder_#00'
          min: 6
          max: 15
        - item: 'firework_tube_#00'
          min: 6
          max: 15
        - item: 'firework_box_#00'
          min: 6
          max: 15

      estimation:
        shift: 10
        spread: 10
        variance: 48
        offset:
          min: 15
          max: 36

      modifiers:
        watchtower_estimation_threshold: 33
        watchtower_estimation_offset: 0
        allow_redig: false
        assemble_items_from_floor: false
        preview_item_assemblage: false
        infection_death_chance: 0.5
        wound_terror_penalty: 0.05
        poison:
          stack_poisoned_items: false
          transgress: false
        citizen_attack:
          ap: 5
          injury: 0.5
          protection: false
        complaints:
          shun: 8
          kill: 6
        carry_extra_bag: false
        meaty_bones_within_town: false
        building_attack_damage: false
        destroy_defense_objects_attack: false
        destroy_defense_objects_attack_ratio: 1
        destroy_defense_objects_attack_max: 0
        camping:
          default_bonus: 0
          map: 'normal'
        red_soul_max_factor: 1.2
        wind_distance: 2
        strict_picto_distribution: false
        sandball_nastyness: 0.1
        massive_respawn_factor: 1
        ghoul_infection_begin: 5
        ghoul_infection_next: 5
        daytime:
          range: [7,18]
          invert: false
        hide_home_upgrade: false
        home_recycling:
          ap: 15
          return: 5
        generosity:
          from_ghoul: 1
          from_last_death_factor: 1
        guard_tower:
          per_use: 10
          max_def: 150
        strange_soil: false
        soul_generation_coef: 1.00

      features:
        camping: true
        words_of_heros: true
        escort:
          enabled: true
          max: 4
        nightmode: true
        shaman: 'normal'
        xml_feed: true
        citizen_alias: false
        ghoul_mode: normal
        hungry_ghouls: false
        all_poison: false
        shun: true
        nightwatch:
          enabled: true
          instant: false
        attacks: 'normal'
        give_all_pictos: true
        enable_pictos: true
        give_soulpoints: true
        last_death: ['r_surlst_#00']
        last_death_day: 5
        survival_picto: null
        free_for_all: false
        free_from_teams: false

      disabled_jobs: ['shaman']
      disabled_roles: []
      disabled_buildings: ['small_vaudoudoll_#00', 'small_bokorsword_#00', 'small_spiritmirage_#00','small_holyrain_#00']

      overrides:
        named_drops: []
        item_groups: []

    small:
      stranger_day_limit: 1
      stranger_citizen_limit: 10

      map:  { min: 12, max: 14, margin: 0.25 }
      ruins: 7
      explorable_ruins: 0

      initial_buildings:  ['small_refine_#00','small_door_closed_#00','item_tagger_#00','small_wallimprove_#00']
      unlocked_buildings: ['small_gather_#02']
      disabled_buildings:
        merge: ['small_novlamps_#00', 'item_soul_blue_static_#00']

      distribute_items:
        replace: ['bplan_box_e_#00', 'bplan_box_e_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'bplan_box_#00', 'firework_powder_#00', 'firework_tube_#00', 'firework_box_#00', 'firework_box_#00']

      spiritual_guide:
        enabled: true
        sp_limit: 100
        citizen: 0.5

      distribution_distance:
        replace:
          - item: 'bplan_box_e_#00'
            min: 4
            max: 90
          - item: 'bplan_box_#00'
            min: 3
            max: 90
          - item: 'firework_powder_#00'
            min: 3
            max: 90
          - item: 'firework_tube_#00'
            min: 3
            max: 90
          - item: 'firework_box_#00'
            min: 3
            max: 90

      instant_pictos:
        merge: ['r_guide_#00', 'r_guard_#00']

      modifiers:
        watchtower_estimation_threshold: 0
        watchtower_estimation_offset: 8
        citizen_attack:
          protection: true
        wind_distance: -1
        strict_picto_distribution: true
        sandball_nastyness: 0.0
        massive_respawn_factor: 0.5
        ghoul_infection_begin: 15

      features:
        shaman: 'none'
        nightmode: false
      
      disabled_roles: ['shaman']

    remote:
      modifiers:
        soul_generation_coef: 1.25

    panda:
      well: { min: 60, max: 90 }

      modifiers:
        infection_death_chance: 0.75
        wound_terror_penalty: 0.2
        building_attack_damage: true
        destroy_defense_objects_attack: true
        destroy_defense_objects_attack_ratio: 50
        destroy_defense_objects_attack_max: 20
        citizen_attack:
          ap: 4
          injury: 0.6
        camping:
          default_bonus: -40
          map: 'hard'
        red_soul_max_factor: 666
        sandball_nastyness: 0.85
        ghoul_infection_begin: 3
        ghoul_infection_next: 3
        hide_home_upgrade: true
        generosity:
          from_ghoul: 1
          from_last_death_factor: 2
        soul_generation_coef: 1.75

      features:
        last_death:
          merge: ['r_suhard_#00']
        last_death_day: 6
        survival_picto: 'r_pande_#00'
        ghoul_mode: airborne

      explorable_ruins: 2

      times:
        exploration:
          normal: '+3min30sec'
          collec: '+5min15sec'

      explorable_ruin_params:
        max_distance: 100

    custom:
      open_town_limit: 2
      open_town_grace: 40
      lock_door_until_full: true
      features:
        give_all_pictos: false
        give_soulpoints: false
        free_from_teams: true
